
services:
  react-app:
    image: frontend
    build:
      context: .
      # args:
      #   HTTP_PROXY: http://your-proxy.com:port
      #   HTTPS_PROXY: http://your-proxy.com:port
    ports:
      - "8060:5173"
    volumes:
      - .:/app
      - /app/node_modules
    # environment:
    #   - http_proxy=http://your-proxy.com:port
    #   - https_proxy=http://your-proxy.com:port
    restart: always
    command: ["npm", "run", "dev", "--", "--host"]
